name: Build and deploy Node.js app to Azure Web App - ci-cd-ssr

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repo

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_927E35A097DC4D10B5C18A2AE8C30092 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5256B33BECE945FDA5BDD415201276B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3E62402A85F484BB8B1342AABAF82EB }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ci-cd-ssr'
          slot-name: 'Production'
          package: '.'  # Deploy the entire source code

      - name: Set startup command on Azure
        uses: azure/webapps-set-startup-command@v1
        with:
          app-name: 'ci-cd-ssr'
          startup-command: 'npm install && npm run build && npm run start'
