name: Build and deploy Node.js app to Azure Web App - ci-cd-ssr

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Use a stable LTS version like 16.x or 18.x

      - name: Install dependencies
        run: |
          npm install  # This generates the `node_modules` folder

      - name: Build the Next.js app
        run: |
          npm run build  # This generates the `.next` folder

      - name: Verify .next folder
        run: |
          ls -alh .next  # List contents of the .next folder to ensure it exists

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next  # Upload only the .next build output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify contents of downloaded artifact
        run: |
          ls -alh  # Verify that the .next folder exists in the downloaded artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_927E35A097DC4D10B5C18A2AE8C30092 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5256B33BECE945FDA5BDD415201276B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3E62402A85F484BB8B1342AABAF82EB }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ci-cd-ssr'
          slot-name: 'Production'
          package: './.next'  # Ensure this points to the build output folder (.next)
